language: node_js
notifications:
  email: false
node_js:
  - '8'
install:
  - yarn --ignore-engines
  - yarn --cwd packages/slate-markdown-editor
  - yarn --cwd example

script:
  - yarn run build:main
deploy:
  skip_cleanup: true
  provider: heroku
  buildpack: nodejs
  api_key:
    secure: "$HEROKU_KEY"
  app: "$HEROKU_APP"