export declare const editCodeOptions: any;
export declare const editBlockquote: any;
export declare const editList: any;
export declare const editCode: any;
export declare const prism: any;
export declare const heading: any;
export declare const inlineMarkdown: any;
export declare const saveState: any;
export declare const noEmpty: any;
